easy_admin:
    entities:
        Color:
            class: AscensoDigital\PerfilBundle\Entity\Color
        Menu:
            class: AscensoDigital\PerfilBundle\Entity\Menu
        Reporte:
            class: AscensoDigital\PerfilBundle\Entity\Reporte
        ReporteCriterio:
            class: AscensoDigital\PerfilBundle\Entity\ReporteCriterio
        ReporteCategoria:
            class: AscensoDigital\PerfilBundle\Entity\ReporteCategoria
        ReporteSeccion:
            class: AscensoDigital\PerfilBundle\Entity\ReporteSeccion
