parameters:
#    ad_perfil.example.class: AscensoDigital\PerfilBundle\Example

services:
    ad_perfil.authentication_listener:
        class: AscensoDigital\PerfilBundle\EventListener\AuthenticationListener
        arguments: [ "%ad_perfil.session_name%" ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onFormLogin }
            - { name: kernel.event_listener, event: security.switch_user, method: onSwitchUser }

    ad_perfil.configurator:
        class: AscensoDigital\PerfilBundle\Configuration\Configurator
        arguments: ['%ad_perfil.config%']

    ad_perfil.filtro.form.type:
        class: AscensoDigital\PerfilBundle\Form\Type\FiltroFormType
        arguments: ["@ad_perfil.configurator", '@security.token_storage','@router']
        tags:
          - { name: form.type, alias: filtro_form_type }

    ad_perfil.request_listener:
        class: AscensoDigital\PerfilBundle\EventListener\RequestListener
        arguments: [ '@ad_perfil.menu_manager' ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    ad_perfil.menu.subscriber:
        class: AscensoDigital\PerfilBundle\EventListener\RegisterMenuSlugSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    ad_perfil.filtro_manager:
        class: AscensoDigital\PerfilBundle\Doctrine\FiltroManager
        arguments: ["@request_stack", "@ad_perfil.configurator"]

    ad_perfil.menu_manager:
        class: AscensoDigital\PerfilBundle\Model\MenuManager
        arguments:
          - '@session'
          - '@doctrine.orm.entity_manager'
          - "%ad_perfil.session_name%"
        public: true

    ad_perfil.perfil_manager:
        class: AscensoDigital\PerfilBundle\Model\PerfilManager
        arguments:
          - '@doctrine.orm.entity_manager'
          - "%ad_perfil.perfil_class%"

    ad_perfil.reporte_manager:
        class: AscensoDigital\PerfilBundle\Model\ReporteManager
        arguments:
          - '@session'
          - '@doctrine.orm.entity_manager'
          - "%ad_perfil.session_name%"
          - '@ad_perfil.perfil_manager'
          - '@security.token_storage'

    ad_perfil.twig_extension:
        class: AscensoDigital\PerfilBundle\Twig\ADPerfilTwigExtension
        arguments: ["@ad_perfil.configurator"]
        public: false
        tags:
            - { name: twig.extension }

    ad_perfil.permiso_voter:
        class: AscensoDigital\PerfilBundle\Security\PermisoVoter
        arguments:
          - '@session'
          - '@doctrine.orm.entity_manager'
          - "%ad_perfil.session_name%"
        public: false
        tags:
            - { name: security.voter }
